eitri-apps:
    - path: ./shopping-vtex-template-shared
      workspace: shared
      alias: shared
      focus: false
      shared: true
    - path: ./shopping-vtex-template-home
      workspace: home
      alias: home
      focus: true
      shared: false
    - path: ./shopping-vtex-template-pdp
      workspace: pdp
      alias: pdp
      focus: false
      shared: false
    - path: ./shopping-vtex-template-account
      workspace: account
      alias: account
      focus: false
      shared: false
    - path: ./shopping-vtex-template-cart
      workspace: cart
      alias: cart
      focus: false
      shared: false
    - path: ./shopping-vtex-template-checkout
      workspace: checkout
      alias: checkout
      focus: false
      shared: false
bottom-tab-view-simulation:
  eitri-apps:
    - slug: "shopping-vtex-template-home"
      title: "Inicio"
      initialization-params:
        type: "string"
        value: "tabIndex=0"
    - slug: "shopping-vtex-template-home"
      title: "Categorias"
      initialization-params:
        type: "string"
        value: "tabIndex=1&route=Categories"
    - slug: "shopping-vtex-template-cart"
      title: "Carrinho"
      initialization-params:
        type: "string"
        value: "tabIndex=2"
    - slug: "shopping-vtex-template-home"
      title: "Ofertas"
      initialization-params:
        type: "string"
        value: "tabIndex=3&route=LandingPage"
    - slug: "shopping-vtex-template-account"
      title: "Perfil"
      initialization-params:
        type: "string"
        value: "tabIndex=4"

application-id: 9022c0fb-885f-4a5f-b99f-7e065189b893